openapi: 3.0.1
info:
  title: Openapi PHP SDK
  description: PHP SDK for MEGA's OpenAPI
  x-cortex-tag: acquia/mc-cf-mega-openapi-php-sdk
  x-cortex-git:
    github:
      repository: acquia/mc-cf-mega-openapi-php-sdk
  x-cortex-owners:
    - type: GROUP
      name: acquia/mc-cf-team
      provider: GITHUB
      description: This team is responsible for development and code review of campaign factory related PRs
    - type: SLACK
      channel: mc-csf-engineering
      notificationsEnabled: true
      description: This channel is used for notify updates, team help, technical discussions
  x-cortex-groups:
    - marketing-cloud
