<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace MauticInc\MEGA\OpenAPI\Model;

class Location
{
    /**
     * @var string
     */
    protected $uuid;
    /**
     * @var \DateTime
     */
    protected $createdAt;
    /**
     * @var \DateTime
     */
    protected $updatedAt;
    /**
     * @var string
     */
    protected $name;
    /**
     * A comma separated list of IP addresses.
     *
     * @var string
     */
    protected $ips;
    /**
     * @var string
     */
    protected $cname;
    /**
     * @var RelLink[]
     */
    protected $links;

    public function getUuid(): string
    {
        return $this->uuid;
    }

    public function setUuid(string $uuid): self
    {
        $this->uuid = $uuid;

        return $this;
    }

    public function getCreatedAt(): \DateTime
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTime $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): \DateTime
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTime $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * A comma separated list of IP addresses.
     */
    public function getIps(): string
    {
        return $this->ips;
    }

    /**
     * A comma separated list of IP addresses.
     */
    public function setIps(string $ips): self
    {
        $this->ips = $ips;

        return $this;
    }

    public function getCname(): string
    {
        return $this->cname;
    }

    public function setCname(string $cname): self
    {
        $this->cname = $cname;

        return $this;
    }

    /**
     * @return RelLink[]
     */
    public function getLinks(): array
    {
        return $this->links;
    }

    /**
     * @param RelLink[] $links
     */
    public function setLinks(array $links): self
    {
        $this->links = $links;

        return $this;
    }
}
