<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace MauticInc\MEGA\OpenAPI\Model;

class PaginationMeta
{
    /**
     * The current page number.
     *
     * @var int
     */
    protected $currentPage;
    /**
     * The ID of the first result in the current set.
     *
     * @var int
     */
    protected $from;
    /**
     * The page number for the last page of results.
     *
     * @var int
     */
    protected $lastPage;
    /**
     * The path to this resource, without query variables attached.
     *
     * @var string
     */
    protected $path;
    /**
     * The number of results per page in the current set.
     *
     * @var int
     */
    protected $perPage;
    /**
     * The ID of the last result in the current set.
     *
     * @var int
     */
    protected $to;
    /**
     * Total number of items in the whole set.
     *
     * @var int
     */
    protected $total;

    /**
     * The current page number.
     */
    public function getCurrentPage(): int
    {
        return $this->currentPage;
    }

    /**
     * The current page number.
     */
    public function setCurrentPage(int $currentPage): self
    {
        $this->currentPage = $currentPage;

        return $this;
    }

    /**
     * The ID of the first result in the current set.
     */
    public function getFrom(): int
    {
        return $this->from;
    }

    /**
     * The ID of the first result in the current set.
     */
    public function setFrom(int $from): self
    {
        $this->from = $from;

        return $this;
    }

    /**
     * The page number for the last page of results.
     */
    public function getLastPage(): int
    {
        return $this->lastPage;
    }

    /**
     * The page number for the last page of results.
     */
    public function setLastPage(int $lastPage): self
    {
        $this->lastPage = $lastPage;

        return $this;
    }

    /**
     * The path to this resource, without query variables attached.
     */
    public function getPath(): string
    {
        return $this->path;
    }

    /**
     * The path to this resource, without query variables attached.
     */
    public function setPath(string $path): self
    {
        $this->path = $path;

        return $this;
    }

    /**
     * The number of results per page in the current set.
     */
    public function getPerPage(): int
    {
        return $this->perPage;
    }

    /**
     * The number of results per page in the current set.
     */
    public function setPerPage(int $perPage): self
    {
        $this->perPage = $perPage;

        return $this;
    }

    /**
     * The ID of the last result in the current set.
     */
    public function getTo(): int
    {
        return $this->to;
    }

    /**
     * The ID of the last result in the current set.
     */
    public function setTo(int $to): self
    {
        $this->to = $to;

        return $this;
    }

    /**
     * Total number of items in the whole set.
     */
    public function getTotal(): int
    {
        return $this->total;
    }

    /**
     * Total number of items in the whole set.
     */
    public function setTotal(int $total): self
    {
        $this->total = $total;

        return $this;
    }
}
