<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace MauticInc\MEGA\OpenAPI\Model;

class ResponseInstance
{
    /**
     * @var Instance
     */
    protected $data;

    public function getData(): Instance
    {
        return $this->data;
    }

    public function setData(Instance $data): self
    {
        $this->data = $data;

        return $this;
    }
}
