<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace MauticInc\MEGA\OpenAPI\Model;

class ValidationError
{
    /**
     * @var string
     */
    protected $name;
    /**
     * The internal error code for this error.
     *
     * @var string
     */
    protected $code;
    /**
     * A plain text description of the error code.
     *
     * @var string
     */
    protected $description;
    /**
     * @var string
     */
    protected $in;

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * The internal error code for this error.
     */
    public function getCode(): string
    {
        return $this->code;
    }

    /**
     * The internal error code for this error.
     */
    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }

    /**
     * A plain text description of the error code.
     */
    public function getDescription(): string
    {
        return $this->description;
    }

    /**
     * A plain text description of the error code.
     */
    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getIn(): string
    {
        return $this->in;
    }

    public function setIn(string $in): self
    {
        $this->in = $in;

        return $this;
    }
}
