<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace MauticInc\MEGA\OpenAPI\Exception;

class LocationReadNotFoundException extends \RuntimeException implements ClientException
{
    private $responseNotFound;

    public function __construct(\MauticInc\MEGA\OpenAPI\Model\ResponseNotFound $responseNotFound)
    {
        parent::__construct('Entity not found.', 404);
        $this->responseNotFound = $responseNotFound;
    }

    public function getResponseNotFound()
    {
        return $this->responseNotFound;
    }
}
